apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    run: hello
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    run: hello
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
    app: hello    
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: gustavogamboa/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
