apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
spec:
  selector:
    matchLabels:
      app: devops-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: "gustavogamboa/devops-demo:latest"

---

apiVersion: v1
kind: Service
metadata:
  name: ilb-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: devops-demo
spec:
  type: LoadBalancer
  selector:
    app: devops-demo
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP

