apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
spec:
  selector:
    matchLabels:
      app: devops-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: "gustavogamboa/devops-demo:latest"

